spring:
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
<<<<<<< HEAD
            client-id: ENC(13+qLO9Ek/O3xlToeAOO1x2zO61/WIsYqebJ4voPHNqjweHGBwneBranu3vzZNgl)
            client-secret: ENC(uajefvIOFDUgV8gxPLqhQeR8wjeP8SJf5evY9nZhNFTcQk9AXInjxTJmDACzcdTs)
            client-authentication-method: client_secret_post
            redirect-uri: ENC(tkZNzB++6rpBDbDY9i7Eb4JrxGz8dEd684KbzNBk+HNzwZadZMOaNTB7bHBn2RxguHMbc2XbuwM=)
=======
            client-id: 604ec5bbcd0045898e4f7f256c00bae5
            client-secret: OyKWsRMnHiKvFza6RU0np25111LAdG09
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/oauth2/callback/kakao
>>>>>>> develop
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname,
              - profile_image,
              - account_email
              - birthday
            client-name: Kakao

#app
app:
  auth:
<<<<<<< HEAD
    token-secret: ENC(i0qGvs4KRuy5GwwvNj29XF32XOes9q1CSxKgfHhXBR8FfZdlx1RJtnDQ/7uA7Wv6JKA4AUoMMyG0nA7kfqaI0xe4YnATjZ7BVpz60HyCuFzn2Cjz1NcDHn8C3tmgmHqYVKRaj1QZbjQ9WxlDCezfO4rTjLoHQNiShhgm1OnwxGxVJ2zZ461eVgQ7bqxS/16V)
=======
    token-secret: 8742F6BEC9F62596C2FFEFF9FA0B9E39303554C06F94AB9B85C8090E3EE87F3CF0BE4BFA244C625E3F691321F9CFF38C228C4C3C91105C23919B16F7E40BE4EC
>>>>>>> develop
    access-token-expiration-msec: 3600000
    refresh-token-expiration-msec: 1209600000
  cors:
    allowed-origins: http://localhost:3000, http://localhost:8080
  oauth2:
<<<<<<< HEAD
    authorized-redirect-uris: http://localhost:3000/oauth2/redirect, myandroidapp://oauth2/redirect, myiosapp://oauth2/redirect, http://43.201.110.47/oauth2/redirect


jasypt:
  encryptor:
    bean : jasyptStringEncryptor
=======
    authorized-redirect-uris: http://localhost:3000/oauth2/redirect, myandroidapp://oauth2/redirect, myiosapp://oauth2/redirect, http://43.201.110.47/oauth2/redirect
>>>>>>> develop
