FROM openjdk:11-jdk
EXPOSE 8080
ARG JAR_FILE=/build/libs/ShallWe-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","-Djasypt.encryptor.password=${JASYPT_PASSWORD}","-Dspring.profiles.active=dev","/app.jar"]
