# logging 설정
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: debug

# console 색상
spring:
  output:
    ansi:
      enabled: always
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

##DB 설정
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: awseb-e-jntpwwy2nv-stack-awsebrdsdatabase-xkusmh3dto0s.ceex1ugfcfad.ap-northeast-2.rds.amazonaws.com:3306
#    username: jin
#    password: 12345678
#
#  #JPA 설정
#  jpa:
#    database-platform:
#    hibernate:
#      ddl-auto: create
#
#    #배포 할 떄는 open-in-view false 설정
#    open-in-view: false
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true


# 오류 처리
server:
  error:
    include-exception: true
    include-stacktrace: always

  #port 설정
  port: 8080