spring:
  application:
    name: ShallWe
  profiles:
    include: key

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8??
    url : ENC(DL/16+vjTN9FoCrWHqqnAFm/8e8CIOiyExoimvVcmozKlj+Yc29O7Vip0c4aGxR2r8wnqEzxaeLfJuIXPveOLg8oLuusPVjCCVEvVcjYxC1e9AyVpFBx5CfOstzyMvz7rVN56t1ulXHtTG2ftAa5+8WdPqOA5/J6)
    username: ENC(KheBba/6grOdPUZa7VfcWQ==)
    password: ENC(XcIJL+39+UgVKAqEl7s7N/wBKLwi6UNn)
  sql:
    init:
      platform: mysql

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug


jasypt:
  encryptor:
    bean : jasyptStringEncryptor
