spring:
  application:
    name: ShallWe
  profiles:
    include: key

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8??
    url : ENC(MqvRgEXlDXIsvq6T2QjEEMa1XwQyF7LV+5nb48wg6yZq5XuAKRogbANrMq8ueoQl6UFlx7QgCAWC/xKSNrSV5FvyZDts0zaxGPvpYZuaiOskIuIikZVqI8AUwf/YgTK+hrjWrsaJXdQxwIVuHNnInCLPrBRYnU72)
    username: ENC(cQHbNerwoH2nwDjyOMY3vw==)
    password: ENC(y9APePFE4JZ3V17g5xmObK2gZ81+m21M)
  sql:
    init:
      platform: mysql

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug


jasypt:
  encryptor:
    bean : jasyptStringEncryptor
