spring:
  application:
    name: ShallWe
  profiles:
    include: key

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8??
    url : jdbc:mysql://shallwe.cakvufpd6nku.ap-northeast-2.rds.amazonaws.com/shallWe?serverTimezone=Asia/Seoul
    username: admin
    password: shallweshallwe!
  sql:
    init:
      platform: mysql

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug


jasypt:
  encryptor:
    bean : jasyptStringEncryptor
