naver-cloud-sms:
  accessKey: ENC(lBWcHO0gZqGL66KEM5K0VU5ybc5XecHYlPCVX+R/U1s=)
  secretKey: ENC(oUTccGxGU2iLbYiVvATfI3d/i+LF/OmAWmgSpYLkl7Ai3YGxJvnYDuGd5OT9dm9yYRfLTwSntvI=)
  serviceId: ENC(x8LaebsWchMekPAubuFkm6zizTVe8JIo26fvLAb6jClpu2IoOiqmzg==)
  senderPhone: ENC(HeG0nnMdj+qhbwhom2rm7t4tViM3D3zz)