cloud:
  aws:
    s3:
      bucket: arn:aws:s3:::shallwebucket
    credentials:
      access-key: AKIAVHBNH5P6CNRVE6XE
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false